In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/Luxury_Housing_Bangalore.csv")
df.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [2]:
df.shape

(101000, 18)

In [3]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='str')

In [4]:
df.dtypes

Property_ID                 str
Micro_Market                str
Project_Name                str
Developer_Name              str
Unit_Size_Sqft          float64
Configuration               str
Ticket_Price_Cr             str
Transaction_Type            str
Buyer_Type                  str
Purchase_Quarter            str
Connectivity_Score      float64
Amenity_Score           float64
Possession_Status           str
Sales_Channel               str
NRI_Buyer                   str
Locality_Infra_Score    float64
Avg_Traffic_Time_Min      int64
Buyer_Comments              str
dtype: object

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  str
 1   Micro_Market          101000 non-null  str
 2   Project_Name          101000 non-null  str
 3   Developer_Name        101000 non-null  str
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  str
 6   Ticket_Price_Cr       90981 non-null   str
 7   Transaction_Type      101000 non-null  str
 8   Buyer_Type            101000 non-null  str
 9   Purchase_Quarter      101000 non-null  str
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  str
 13  Sales_Channel         101000 non-null  str
 14  NRI_Buyer             101000 non-null  str
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   str
dtypes: float64(4), int64(1), str(13)
memory usage: 13.9 MB

In [6]:
df.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [7]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [8]:
df['Ticket_Price_Cr'].dtype

In [9]:
#Inspecting Ticket_Price_Cr column before cleaning
df_raw = pd.read_csv("../data/raw/Luxury_Housing_Bangalore.csv")
df_raw['Ticket_Price_Cr'].str.contains('Cr', na=False).sum()
df_raw[df_raw['Ticket_Price_Cr'].str.contains('Cr', na=False)].head(5)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
5,PROP000006,YELAHANKA,Project_5,Brigade,4290.0,4bhk,₹9.82 Cr,Secondary,HNI,2023-09-30,7.936068,NaN,Launch,Online,no,5.154027,16,Underpriced for location.
21,PROP000022,Whitefield,Project_21,Prestige,8741.0,5bhk+,₹8.68 Cr,Secondary,CXO,2024-06-30,5.910686,8.653824,Ready to move,NRI Desk,yes,8.344247,32,Underpriced for location.
23,PROP000024,yelahanka,Project_23,Puravankara,4133.0,4bhk,₹13.11 Cr,Primary,HNI,2024-12-31,5.479547,6.618180,Launch,Online,yes,9.312456,56,Agent was not responsive.
24,PROP000025,Mg Road,Project_24,L&T Realty,NaN,3Bhk,₹13.64 Cr,Primary,Other,2024-03-31,9.300782,9.464122,Under construction,Online,no,8.127972,43,Agent was not responsive.
38,PROP000039,HEBBAL,Project_38,Embassy,8680.0,3bhk,₹14.11 Cr,Secondary,CXO,2023-09-30,7.038034,9.771873,Ready to move,Online,no,8.684605,37,Will buy after possession.

In [10]:
df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].astype(str)

# Remove ₹ symbol
df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].str.replace('₹', '', regex=False)

# Remove 'Cr'
df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].str.replace('Cr', '', regex=False)

# Remove spaces
df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].str.strip()

# Convert to numeric
df['Ticket_Price_Cr'] = pd.to_numeric(df['Ticket_Price_Cr'], errors='coerce')

In [11]:
df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].fillna(df['Ticket_Price_Cr'].median())

In [12]:
df['Ticket_Price_Cr'].isnull().sum()

np.int64(0)

In [13]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr             0
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [14]:
df[['Unit_Size_Sqft', 'Amenity_Score']].describe()

       Unit_Size_Sqft  Amenity_Score
count    90954.000000   90910.000000
mean      5972.274765       7.503663
std       1783.397836       1.440758
min         -1.000000       5.000224
25%       4477.250000       6.260329
50%       5990.000000       7.499123
75%       7497.000000       8.752207
max       8999.000000       9.999865

In [15]:
df['Unit_Size_Sqft'].sort_values(ascending=False).head(10)

32211    8999.0
82408    8999.0
85354    8999.0
37921    8999.0
61051    8999.0
71363    8999.0
20933    8999.0
98861    8999.0
62448    8999.0
79206    8999.0
Name: Unit_Size_Sqft, dtype: float64

In [16]:
df['Unit_Size_Sqft'].sort_values().head(10)

23079   -1.0
23469   -1.0
32911   -1.0
43770   -1.0
15393   -1.0
33414   -1.0
60831   -1.0
15734   -1.0
80037   -1.0
60711   -1.0
Name: Unit_Size_Sqft, dtype: float64

In [17]:
df['Unit_Size_Sqft'].value_counts().head(10)

Unit_Size_Sqft
-1.0       505
 4058.0     33
 6868.0     32
 7617.0     31
 4210.0     30
 7279.0     30
 5084.0     30
 8864.0     28
 8005.0     28
 5757.0     28
Name: count, dtype: int64

In [18]:
df['Unit_Size_Sqft'] = df['Unit_Size_Sqft'].replace(-1, pd.NA)

In [19]:
df['Unit_Size_Sqft'] = df['Unit_Size_Sqft'].fillna(df['Unit_Size_Sqft'].median())

In [20]:
df['Unit_Size_Sqft'].isnull().sum()

np.int64(0)

In [21]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft              0
Configuration               0
Ticket_Price_Cr             0
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [22]:
df['Amenity_Score'].value_counts().head(10)

Amenity_Score
6.756185    2
5.211055    2
7.945176    2
7.425450    2
6.172892    2
5.835004    2
9.243307    2
7.861204    2
5.545170    2
8.158959    2
Name: count, dtype: int64

In [23]:
df['Amenity_Score'].isnull().sum()

np.int64(10090)

In [24]:
df['Amenity_Score'] = df['Amenity_Score'].fillna(df['Amenity_Score'].median())

In [25]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft              0
Configuration               0
Ticket_Price_Cr             0
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score               0
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [26]:
df = df.drop('Buyer_Comments', axis=1)

In [27]:
df.isnull().sum()

Property_ID             0
Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Configuration           0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
dtype: int64

In [28]:
df.dtypes

Property_ID                 str
Micro_Market                str
Project_Name                str
Developer_Name              str
Unit_Size_Sqft           object
Configuration               str
Ticket_Price_Cr         float64
Transaction_Type            str
Buyer_Type                  str
Purchase_Quarter            str
Connectivity_Score      float64
Amenity_Score           float64
Possession_Status           str
Sales_Channel               str
NRI_Buyer                   str
Locality_Infra_Score    float64
Avg_Traffic_Time_Min      int64
dtype: object

In [29]:
df.nunique()

Property_ID             100000
Micro_Market                48
Project_Name               500
Developer_Name              11
Unit_Size_Sqft            6000
Configuration                9
Ticket_Price_Cr          72851
Transaction_Type             2
Buyer_Type                   5
Purchase_Quarter             8
Connectivity_Score      100000
Amenity_Score            90001
Possession_Status            3
Sales_Channel                4
NRI_Buyer                    2
Locality_Infra_Score    100000
Avg_Traffic_Time_Min       105
dtype: int64

In [30]:
df['Unit_Size_Sqft'] = pd.to_numeric(df['Unit_Size_Sqft'], errors='coerce')

In [31]:
df['Unit_Size_Sqft'].dtype

dtype('float64')

In [32]:
df['Unit_Size_Sqft'].value_counts()

Unit_Size_Sqft
6004.0    10570
4058.0       33
6868.0       32
7617.0       31
4210.0       30
          ...
6737.0        5
3070.0        5
6688.0        4
4854.0        4
7918.0        4
Name: count, Length: 6000, dtype: int64

In [33]:
df.dtypes

Property_ID                 str
Micro_Market                str
Project_Name                str
Developer_Name              str
Unit_Size_Sqft          float64
Configuration               str
Ticket_Price_Cr         float64
Transaction_Type            str
Buyer_Type                  str
Purchase_Quarter            str
Connectivity_Score      float64
Amenity_Score           float64
Possession_Status           str
Sales_Channel               str
NRI_Buyer                   str
Locality_Infra_Score    float64
Avg_Traffic_Time_Min      int64
dtype: object

In [34]:
cols = ['Micro_Market','Developer_Name','Configuration',
        'Transaction_Type','Buyer_Type','Sales_Channel','Possession_Status']

for col in cols:
    df[col] = df[col].str.strip().str.lower()

In [35]:
df['Price_per_Sqft'] = (df['Ticket_Price_Cr'] * 10000000) / df['Unit_Size_Sqft']

In [36]:
df["Micro_Market"] = df["Micro_Market"].str.title()
df["Developer_Name"] = df["Developer_Name"].str.title()

In [37]:
df["Micro_Market"].value_counts()

Micro_Market
Jp Nagar             6441
Sarjapur Road        6435
Bannerghatta Road    6427
Jayanagar            6427
Mg Road              6347
Whitefield           6340
Indiranagar          6323
Kanakapura Road      6292
Yelahanka            6290
Bellary Road         6277
Rajajinagar          6274
Electronic City      6273
Domlur               6250
Hebbal               6235
Hennur Road          6216
Koramangala          6153
Name: count, dtype: int64

In [38]:
df["Developer_Name"].value_counts()

Developer_Name
Prestige             9318
Snn Raj              9309
Brigade              9240
L&T Realty           9225
Godrej               9215
Total Environment    9209
Puravankara          9166
Embassy              9164
Rmz                  9092
Sobha                9043
Tata Housing         9019
Name: count, dtype: int64

In [39]:
df["Transaction_Type"].value_counts(dropna=False)

Transaction_Type
secondary    50506
primary      50494
Name: count, dtype: int64

In [40]:
df["Transaction_Type"] = df["Transaction_Type"].astype(str).str.strip().str.title()

df["Booking_Flag"] = df["Transaction_Type"].apply(
    lambda x: 1 if x == "Primary" else 0
)

df["Booking_Status"] = df["Booking_Flag"].map({
    1: "Booked",
    0: "Not Booked"
})

In [41]:
df["Transaction_Type"].value_counts()

Transaction_Type
Secondary    50506
Primary      50494
Name: count, dtype: int64

In [42]:
df["Booking_Flag"].value_counts()

Booking_Flag
0    50506
1    50494
Name: count, dtype: int64

In [43]:
df["Booking_Status"].value_counts()

Booking_Status
Not Booked    50506
Booked        50494
Name: count, dtype: int64

In [44]:
df["Purchase_Quarter"] = pd.to_datetime(df["Purchase_Quarter"])
df["Quarter_Number"] = df["Purchase_Quarter"].dt.quarter

In [45]:
df["Quarter_Number"].value_counts().sort_index()

Quarter_Number
1    25281
2    25263
3    25301
4    25155
Name: count, dtype: int64

In [46]:
df[["Purchase_Quarter", "Quarter_Number"]].head(20)

   Purchase_Quarter  Quarter_Number
0        2025-03-31               1
1        2024-06-30               2
2        2023-12-31               4
3        2024-03-31               1
4        2024-12-31               4
5        2023-09-30               3
6        2025-03-31               1
7        2025-03-31               1
8        2024-03-31               1
9        2023-09-30               3
10       2024-06-30               2
11       2024-03-31               1
12       2024-03-31               1
13       2023-12-31               4
14       2024-06-30               2
15       2024-03-31               1
16       2023-12-31               4
17       2024-03-31               1
18       2024-12-31               4
19       2024-09-30               3

In [47]:
# Validate
print("Minimum value before cleaning:", df["Ticket_Price_Cr"].min())
print("Invalid rows:", (df["Ticket_Price_Cr"] <= 0).sum())

Minimum value before cleaning: -1.42
Invalid rows: 5

In [48]:
# Remove invalid negative price rows
df = df[df["Ticket_Price_Cr"] > 0]

# Verify
print("Min price after cleaning:", df["Ticket_Price_Cr"].min())

# Save cleaned dataset
df.to_csv("cleaned_luxury_housing.csv", index=False)

Min price after cleaning: 0.66